export type ObjectKey = "invoice" | "purchase_order" | "goods_receipt" | "review_response"

export const OBJECT_SCHEMAS: Record<ObjectKey, any> = {
  invoice: {
    invoiceId: "string",
    invoiceNumber: "string",
    vendorId: "string",
    vendorName: "string",
    totalAmount: "number",
    invoiceDate: "date",
    dueDate: "date",
    documentType: "string",
    poReference: "string",
    lineItems: [
      {
        description: "string",
        amount: "number",
        quantity: "number",
        glCode: "string",
        taxAmount: "number",
        taxCategory: "string",
        department: "string",
        category: "string",
      },
    ],
    paymentTerms: "string",
    taxRate: "number",
    discountAmount: "number",
    netAmount: "number",
    documentStructure: "object",
    hasValidFormat: "boolean",
    structureAnomalies: "array",
    invoiceType: "string",
    requiresPoMatch: "boolean",
    requiresGrnMatch: "boolean",
    sourceSystem: "string",
    documentVersion: "string",
    digitalSignature: "string",
    attachmentCount: "number",
    language: "string",
    requiresTranslation: "boolean",
    toleranceRules: {
      pricePercent: "number",
      quantityPercent: "number",
      dateDays: "number",
      autoApprovalLimit: "number",
    },
    matchingResult: {
      overallMatch: "boolean",
      vendorMatch: "boolean",
      lineItemMatches: "array",
      quantityMatch: "boolean",
      priceMatch: "boolean",
      discrepancies: "array",
    },
    toleranceResult: {
      applied: "boolean",
      acceptableVariances: "array",
      unacceptableVariances: "array",
      withinTolerance: "boolean",
    },
    paymentVoucher: {
      voucherNumber: "string",
      paymentAmount: "number",
      paymentDueDate: "date",
      paymentMethod: "string",
    },
    journalEntry: {
      entryNumber: "string",
      debitEntries: "array",
      creditEntries: "array",
      postingDate: "date",
    },
    taxRecord: {
      recordId: "string",
      taxableAmount: "number",
      taxAmount: "number",
      filingPeriod: "string",
    },
    auditTrail: {
      auditId: "string",
      processSteps: "array",
      decisionPoints: "array",
      timestamps: "array",
    },
    reports: {
      summaryUrl: "string",
      exceptionUrl: "string",
      vendorReportUrl: "string",
    },
    payment: {
      transactionId: "string",
      status: "string",
      confirmationNumber: "string",
      executedDate: "date",
    },
    systemSync: {
      erpStatus: "string",
      accountingStatus: "string",
      timestamp: "date",
    },
    triggeredWorkflows: "array",
    activityLog: {
      logId: "string",
      entries: "array",
    },
    syncStatus: {
      completed: "boolean",
      systems: "array",
      timestamp: "date",
    },
    notifications: {
      sent: "boolean",
    },
    status: "string",
    completedAt: "date",
    completedBy: "string",
    finalNotifications: {
      vendorNotified: "boolean",
      financeNotified: "boolean",
      timestamp: "date",
    },
  },
  purchase_order: {
    poNumber: "string",
    vendorId: "string",
    totalAmount: "number",
    lineItems: "array",
    paymentTerms: "string",
    status: "string",
  },
  goods_receipt: {
    grnNumber: "string",
    poNumber: "string",
    lineItems: "array",
    receivedDate: "date",
    status: "string",
  },
  // Map review_response to the human review response structure used across app
  review_response: {
    decision: "string",
    comments: "string",
    reviewedBy: "string",
  },
}
